Task 53
Findoss/Hunt-map pull request #65
Opened 2022-02-25 21:33 UTC by PavelEgorov-ru

Оставил комментарии в коде, где было непонятно. Пока совсем не понимаю, как лучше сделать в map.

2022-02-26 10:09 UTC, PavelEgorov-ru commented
Предлагаю стили, где есть логика, оставлять в переменных, чтобы более читаемо было. Пример: Sidebar

2022-02-26 10:36 UTC, Findoss requested changes
```const styleSectionLang = cn(`${styles.section} ${styles.section__lang}`);``` - показал как проще

с сложными стилями где есть много логики можно оставить в отдельной константой, но в качестве исключения. Нет смысла создавать константу на 1 строку (это куча кода ради кода)

2022-02-26 10:36 UTC, Findoss commented on src/components/checkbox/checkbox.module.css
> +.label_activ {
опечатка
```suggestion
.label_active {
```

2022-02-26 10:36 UTC, Findoss commented on src/components/checkbox/index.tsx
> +    [styles.label_activ]: checked,
опечатка

```suggestion
    [styles.label_active]: checked,
```

2022-02-26 10:36 UTC, Findoss commented on src/containers/sidebar/sections/index.tsx
> +  const styleSectionAdv = cn(`${styles.section__adv}`);
adv = реклама

2022-02-26 10:36 UTC, Findoss commented on src/containers/sidebar/sections/index.tsx
> +  const styleSectionBr = cn(`${styles.section__br}`);
br костыль на отступ

2022-02-26 10:36 UTC, Findoss commented on src/containers/sidebar/sections/index.tsx
> +        <SectionLang className={styleSectionLang} />
можно проще 
```suggestion
        <SectionLang className={cn(styles.section, styles.section__lang)} />
```

2022-02-26 10:36 UTC, Findoss commented on src/containers/sidebar/sections/tools/index.tsx
> +  const styleSection = cn(className);
```suggestion
```

2022-02-26 10:36 UTC, Findoss commented on src/containers/sidebar/sections/tools/index.tsx
>    className?: string;
что бы не было путаницы, что за класс
```suggestion
  extraClass?: string;
```

2022-02-26 10:36 UTC, Findoss commented on src/containers/sidebar/sections/tools/index.tsx
>  export const SectionTools = ({ className }: Props) => {
```suggestion
export const SectionTools = ({ extraClass }: Props) => {
```

2022-02-26 10:36 UTC, Findoss commented on src/containers/sidebar/sections/tools/index.tsx
> +    <div className={styleSection}>
```suggestion
    <div className={extraClass}>
```

2022-02-26 10:36 UTC, Findoss commented on src/containers/sidebar/sections/tools/index.tsx
> +  const styleContainer = cn(`${styles.container}`);
```suggestion
```

2022-02-26 10:36 UTC, Findoss commented on src/containers/sidebar/sections/tools/index.tsx
> +      <div className={styleContainer}>
```suggestion
      <div className={styles.container}>
```

2022-02-26 13:21 UTC, PavelEgorov-ru commented
через час продолжу, решу конфликт, не увидел коммиты

2022-02-26 15:32 UTC, PavelEgorov-ru commented
работоспособность проверил

2022-02-28 17:11 UTC, Findoss approved these changes

2022-02-28 18:00 UTC, merged